# Generated by Django 6.1 on 2026-08-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='libelle',
            field=models.CharField(help_text='Ex : Algorithmique / Pseudo-Code, Web Client / HTML & CSS ...', max_length=100),
        ),
    ]
